import { ISpendingPlan } from "@/core/fund-saving-plant/models"
import { IBudget, ICategoryStatistic, IDialogFlags } from "@/core/fund-saving-target/models"

// Mock categories
export const categories = [
    "Ăn uống",
    "Ăn vặt",
    "Đi lại",
    "Mua sắm",
    "Giải trí",
    "Hóa đơn",
    "Quà tặng",
    "Khoản vay",
    "Y tế",
    "Giáo dục",
    "Nhà cửa",
    "Khác",
]

// Mock account sources
export const accountSources = [
    { id: "1", name: "Ví tiền mặt" },
    { id: "2", name: "Tài khoản ngân hàng" },
    { id: "3", name: "Thẻ tín dụng" },
]

// Notify options
export const notifyOptions = [
    { value: 0, label: "Không thông báo" },
    { value: 1, label: "Trước 1 ngày" },
    { value: 2, label: "Trước 2 ngày" },
    { value: 3, label: "Trước 3 ngày" },
    { value: 7, label: "Trước 1 tuần" },
]

// Initial empty plan
export const initEmptyPlan: ISpendingPlan = {
    id: "",
    title: "",
    description: "",
    amount: 0,
    plannedDate: new Date().toISOString(),
    category: "",
    status: "pending",
    notifyBefore: 1,
    accountSourceId: "",
    accountSourceName: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
}

// Initial empty budget
export const initEmptyBudget: IBudget = {
    id: "",
    category: "",
    budgetAmount: 0,
    spentAmount: 0,
    remainingAmount: 0,
    startDate: new Date().toISOString(),
    endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
}

// Initial dialog flags
export const initDialogFlags: IDialogFlags = {
    isDialogCreatePlanOpen: false,
    isDialogEditPlanOpen: false,
    isDialogDetailPlanOpen: false,
    isDialogDeletePlanOpen: false,
    isDialogCreateBudgetOpen: false,
    isDialogEditBudgetOpen: false,
    isDialogDetailBudgetOpen: false,
    isDialogDeleteBudgetOpen: false,
}

export const mockSpendingPlans: ISpendingPlan[] = [
    {
        id: "1",
        title: "Tiền thuê nhà tháng 6",
        description: "Thanh toán tiền thuê nhà tháng 6/2024",
        amount: 5000000,
        plannedDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days from now
        category: "Nhà cửa",
        status: "pending",
        notifyBefore: 1,
        accountSourceName: "Ví tiền mặt",
        accountSourceId: "1",
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "2",
        title: "Trả nợ bạn Minh",
        description: "Trả tiền mượn tháng trước",
        amount: 500000,
        plannedDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days from now
        category: "Khoản vay",
        status: "pending",
        notifyBefore: 1,
        accountSourceName: "Tài khoản ngân hàng",
        accountSourceId: "2",
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "3",
        title: "Tiền điện tháng 6",
        description: "Thanh toán tiền điện tháng 6/2024",
        amount: 1200000,
        plannedDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day from now
        category: "Hóa đơn",
        status: "pending",
        notifyBefore: 1,
        accountSourceName: "Tài khoản ngân hàng",
        accountSourceId: "2",
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "4",
        title: "Phí bảo hiểm y tế",
        description: "Thanh toán phí bảo hiểm y tế năm 2024",
        amount: 750000,
        plannedDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
        category: "Bảo hiểm",
        status: "pending",
        notifyBefore: 2,
        accountSourceName: "Tài khoản ngân hàng",
        accountSourceId: "2",
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "5",
        title: "Trả góp laptop",
        description: "Thanh toán trả góp laptop kỳ 3/12",
        amount: 1500000,
        plannedDate: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(), // 6 days from now
        category: "Trả góp",
        status: "pending",
        notifyBefore: 3,
        accountSourceName: "Tài khoản ngân hàng",
        accountSourceId: "2",
        createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "6",
        title: "Tiền nước tháng 6",
        description: "Thanh toán tiền nước tháng 6/2024",
        amount: 350000,
        plannedDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
        category: "Hóa đơn",
        status: "pending",
        notifyBefore: 1,
        accountSourceName: "Ví điện tử MoMo",
        accountSourceId: "3",
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "7",
        title: "Phí quản lý chung cư",
        description: "Thanh toán phí quản lý chung cư tháng 6/2024",
        amount: 700000,
        plannedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago (completed)
        category: "Nhà cửa",
        status: "completed",
        notifyBefore: 1,
        accountSourceName: "Ví điện tử MoMo",
        accountSourceId: "3",
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "8",
        title: "Đóng học phí con",
        description: "Đóng học phí học kỳ hè cho con",
        amount: 3200000,
        plannedDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
        category: "Giáo dục",
        status: "pending",
        notifyBefore: 5,
        accountSourceName: "Tài khoản ngân hàng",
        accountSourceId: "2",
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "9",
        title: "Tiền Internet tháng 6",
        description: "Thanh toán cước Internet tháng 6/2024",
        amount: 250000,
        plannedDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(), // 8 days from now (won't show in upcoming)
        category: "Hóa đơn",
        status: "pending",
        notifyBefore: 2,
        accountSourceName: "Ví điện tử ZaloPay",
        accountSourceId: "4",
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "10",
        title: "Bảo dưỡng xe máy",
        description: "Đem xe đi bảo dưỡng định kỳ",
        amount: 450000,
        plannedDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(), // 12 days from now (won't show in upcoming)
        category: "Phương tiện",
        status: "pending",
        notifyBefore: 2,
        accountSourceName: "Ví tiền mặt",
        accountSourceId: "1",
        createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    }
]

export const mockBudgets: IBudget[] = [
    {
        id: "1",
        category: "Ăn vặt",
        budgetAmount: 300000,
        spentAmount: 150000,
        remainingAmount: 150000,
        startDate: new Date(new Date().setDate(1)).toISOString(), // First day of current month
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(), // Last day of current month
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "11",
        category: "Ăn vặt",
        budgetAmount: 300000,
        spentAmount: 150000,
        remainingAmount: 150000,
        startDate: new Date(new Date().setDate(1)).toISOString(), // First day of current month
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(), // Last day of current month
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "2",
        category: "Ăn uống",
        budgetAmount: 2000000,
        spentAmount: 1800000,
        remainingAmount: 200000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "3",
        category: "Đi lại",
        budgetAmount: 500000,
        spentAmount: 600000,
        remainingAmount: -100000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "exceeded",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "4",
        category: "Mua sắm",
        budgetAmount: 1500000,
        spentAmount: 1200000,
        remainingAmount: 300000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "5",
        category: "Giải trí",
        budgetAmount: 500000,
        spentAmount: 450000,
        remainingAmount: 50000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "6",
        category: "Nhà cửa",
        budgetAmount: 6000000,
        spentAmount: 5700000,
        remainingAmount: 300000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "7",
        category: "Hóa đơn",
        budgetAmount: 2000000,
        spentAmount: 1800000,
        remainingAmount: 200000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "8",
        category: "Bảo hiểm",
        budgetAmount: 750000,
        spentAmount: 750000,
        remainingAmount: 0,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "completed",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "9",
        category: "Giáo dục",
        budgetAmount: 3500000,
        spentAmount: 3200000,
        remainingAmount: 300000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: "10",
        category: "Phương tiện",
        budgetAmount: 800000,
        spentAmount: 450000,
        remainingAmount: 350000,
        startDate: new Date(new Date().setDate(1)).toISOString(),
        endDate: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString(),
        status: "active",
        createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        updatedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    }
]

export const mockCategoryStatistics: ICategoryStatistic[] = [
    {
        category: "Ăn vặt",
        totalSpent: 150000,
        budgetAmount: 300000,
        percentage: 50,
        transactions: 5,
    },
    {
        category: "Ăn uống",
        totalSpent: 1800000,
        budgetAmount: 2000000,
        percentage: 90,
        transactions: 15,
    },
    {
        category: "Đi lại",
        totalSpent: 600000,
        budgetAmount: 500000,
        percentage: 120,
        transactions: 10,
    },
    {
        category: "Mua sắm",
        totalSpent: 1200000,
        budgetAmount: 1500000,
        percentage: 80,
        transactions: 3,
    },
    {
        category: "Giải trí",
        totalSpent: 450000,
        budgetAmount: 500000,
        percentage: 90,
        transactions: 4,
    },
    {
        category: "Nhà cửa",
        totalSpent: 5700000,
        budgetAmount: 6000000,
        percentage: 95,
        transactions: 2,
    },
    {
        category: "Hóa đơn",
        totalSpent: 1800000,
        budgetAmount: 2000000,
        percentage: 90,
        transactions: 3,
    },
    {
        category: "Bảo hiểm",
        totalSpent: 750000,
        budgetAmount: 750000,
        percentage: 100,
        transactions: 1,
    },
    {
        category: "Giáo dục",
        totalSpent: 3200000,
        budgetAmount: 3500000,
        percentage: 91,
        transactions: 1,
    },
    {
        category: "Phương tiện",
        totalSpent: 450000,
        budgetAmount: 800000,
        percentage: 56,
        transactions: 1,
    }
]