export const FUND_SAVING_PLANT_RETRY_QUERY = 2
export const GET_ALL_FUND_SAVING_PLANT_KEY = 'PLANT/ALL_FUND_SAVING_PLANT'
export const GET_FUND_SAVING_PLANT_BY_ID_KEY = 'PLANT/FUND_SAVING_PLANT_BY_ID'